################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Source/StatisticsFunctions/StatisticsFunctions.c \
../Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Source/StatisticsFunctions/arm_absmax_f16.c \
../Source/StatisticsFunctions/arm_absmax_f32.c \
../Source/StatisticsFunctions/arm_absmax_f64.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Source/StatisticsFunctions/arm_absmax_q15.c \
../Source/StatisticsFunctions/arm_absmax_q31.c \
../Source/StatisticsFunctions/arm_absmax_q7.c \
../Source/StatisticsFunctions/arm_absmin_f16.c \
../Source/StatisticsFunctions/arm_absmin_f32.c \
../Source/StatisticsFunctions/arm_absmin_f64.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Source/StatisticsFunctions/arm_absmin_q15.c \
../Source/StatisticsFunctions/arm_absmin_q31.c \
../Source/StatisticsFunctions/arm_absmin_q7.c \
../Source/StatisticsFunctions/arm_accumulate_f16.c \
../Source/StatisticsFunctions/arm_accumulate_f32.c \
../Source/StatisticsFunctions/arm_accumulate_f64.c \
../Source/StatisticsFunctions/arm_entropy_f16.c \
../Source/StatisticsFunctions/arm_entropy_f32.c \
../Source/StatisticsFunctions/arm_entropy_f64.c \
../Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Source/StatisticsFunctions/arm_max_f16.c \
../Source/StatisticsFunctions/arm_max_f32.c \
../Source/StatisticsFunctions/arm_max_f64.c \
../Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Source/StatisticsFunctions/arm_max_q15.c \
../Source/StatisticsFunctions/arm_max_q31.c \
../Source/StatisticsFunctions/arm_max_q7.c \
../Source/StatisticsFunctions/arm_mean_f16.c \
../Source/StatisticsFunctions/arm_mean_f32.c \
../Source/StatisticsFunctions/arm_mean_f64.c \
../Source/StatisticsFunctions/arm_mean_q15.c \
../Source/StatisticsFunctions/arm_mean_q31.c \
../Source/StatisticsFunctions/arm_mean_q7.c \
../Source/StatisticsFunctions/arm_min_f16.c \
../Source/StatisticsFunctions/arm_min_f32.c \
../Source/StatisticsFunctions/arm_min_f64.c \
../Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Source/StatisticsFunctions/arm_min_q15.c \
../Source/StatisticsFunctions/arm_min_q31.c \
../Source/StatisticsFunctions/arm_min_q7.c \
../Source/StatisticsFunctions/arm_mse_f16.c \
../Source/StatisticsFunctions/arm_mse_f32.c \
../Source/StatisticsFunctions/arm_mse_f64.c \
../Source/StatisticsFunctions/arm_mse_q15.c \
../Source/StatisticsFunctions/arm_mse_q31.c \
../Source/StatisticsFunctions/arm_mse_q7.c \
../Source/StatisticsFunctions/arm_power_f16.c \
../Source/StatisticsFunctions/arm_power_f32.c \
../Source/StatisticsFunctions/arm_power_f64.c \
../Source/StatisticsFunctions/arm_power_q15.c \
../Source/StatisticsFunctions/arm_power_q31.c \
../Source/StatisticsFunctions/arm_power_q7.c \
../Source/StatisticsFunctions/arm_rms_f16.c \
../Source/StatisticsFunctions/arm_rms_f32.c \
../Source/StatisticsFunctions/arm_rms_q15.c \
../Source/StatisticsFunctions/arm_rms_q31.c \
../Source/StatisticsFunctions/arm_std_f16.c \
../Source/StatisticsFunctions/arm_std_f32.c \
../Source/StatisticsFunctions/arm_std_f64.c \
../Source/StatisticsFunctions/arm_std_q15.c \
../Source/StatisticsFunctions/arm_std_q31.c \
../Source/StatisticsFunctions/arm_var_f16.c \
../Source/StatisticsFunctions/arm_var_f32.c \
../Source/StatisticsFunctions/arm_var_f64.c \
../Source/StatisticsFunctions/arm_var_q15.c \
../Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Source/StatisticsFunctions/StatisticsFunctions.o \
./Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Source/StatisticsFunctions/arm_absmax_f16.o \
./Source/StatisticsFunctions/arm_absmax_f32.o \
./Source/StatisticsFunctions/arm_absmax_f64.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Source/StatisticsFunctions/arm_absmax_q15.o \
./Source/StatisticsFunctions/arm_absmax_q31.o \
./Source/StatisticsFunctions/arm_absmax_q7.o \
./Source/StatisticsFunctions/arm_absmin_f16.o \
./Source/StatisticsFunctions/arm_absmin_f32.o \
./Source/StatisticsFunctions/arm_absmin_f64.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Source/StatisticsFunctions/arm_absmin_q15.o \
./Source/StatisticsFunctions/arm_absmin_q31.o \
./Source/StatisticsFunctions/arm_absmin_q7.o \
./Source/StatisticsFunctions/arm_accumulate_f16.o \
./Source/StatisticsFunctions/arm_accumulate_f32.o \
./Source/StatisticsFunctions/arm_accumulate_f64.o \
./Source/StatisticsFunctions/arm_entropy_f16.o \
./Source/StatisticsFunctions/arm_entropy_f32.o \
./Source/StatisticsFunctions/arm_entropy_f64.o \
./Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Source/StatisticsFunctions/arm_max_f16.o \
./Source/StatisticsFunctions/arm_max_f32.o \
./Source/StatisticsFunctions/arm_max_f64.o \
./Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Source/StatisticsFunctions/arm_max_q15.o \
./Source/StatisticsFunctions/arm_max_q31.o \
./Source/StatisticsFunctions/arm_max_q7.o \
./Source/StatisticsFunctions/arm_mean_f16.o \
./Source/StatisticsFunctions/arm_mean_f32.o \
./Source/StatisticsFunctions/arm_mean_f64.o \
./Source/StatisticsFunctions/arm_mean_q15.o \
./Source/StatisticsFunctions/arm_mean_q31.o \
./Source/StatisticsFunctions/arm_mean_q7.o \
./Source/StatisticsFunctions/arm_min_f16.o \
./Source/StatisticsFunctions/arm_min_f32.o \
./Source/StatisticsFunctions/arm_min_f64.o \
./Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Source/StatisticsFunctions/arm_min_q15.o \
./Source/StatisticsFunctions/arm_min_q31.o \
./Source/StatisticsFunctions/arm_min_q7.o \
./Source/StatisticsFunctions/arm_mse_f16.o \
./Source/StatisticsFunctions/arm_mse_f32.o \
./Source/StatisticsFunctions/arm_mse_f64.o \
./Source/StatisticsFunctions/arm_mse_q15.o \
./Source/StatisticsFunctions/arm_mse_q31.o \
./Source/StatisticsFunctions/arm_mse_q7.o \
./Source/StatisticsFunctions/arm_power_f16.o \
./Source/StatisticsFunctions/arm_power_f32.o \
./Source/StatisticsFunctions/arm_power_f64.o \
./Source/StatisticsFunctions/arm_power_q15.o \
./Source/StatisticsFunctions/arm_power_q31.o \
./Source/StatisticsFunctions/arm_power_q7.o \
./Source/StatisticsFunctions/arm_rms_f16.o \
./Source/StatisticsFunctions/arm_rms_f32.o \
./Source/StatisticsFunctions/arm_rms_q15.o \
./Source/StatisticsFunctions/arm_rms_q31.o \
./Source/StatisticsFunctions/arm_std_f16.o \
./Source/StatisticsFunctions/arm_std_f32.o \
./Source/StatisticsFunctions/arm_std_f64.o \
./Source/StatisticsFunctions/arm_std_q15.o \
./Source/StatisticsFunctions/arm_std_q31.o \
./Source/StatisticsFunctions/arm_var_f16.o \
./Source/StatisticsFunctions/arm_var_f32.o \
./Source/StatisticsFunctions/arm_var_f64.o \
./Source/StatisticsFunctions/arm_var_q15.o \
./Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Source/StatisticsFunctions/StatisticsFunctions.d \
./Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Source/StatisticsFunctions/arm_absmax_f16.d \
./Source/StatisticsFunctions/arm_absmax_f32.d \
./Source/StatisticsFunctions/arm_absmax_f64.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Source/StatisticsFunctions/arm_absmax_q15.d \
./Source/StatisticsFunctions/arm_absmax_q31.d \
./Source/StatisticsFunctions/arm_absmax_q7.d \
./Source/StatisticsFunctions/arm_absmin_f16.d \
./Source/StatisticsFunctions/arm_absmin_f32.d \
./Source/StatisticsFunctions/arm_absmin_f64.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Source/StatisticsFunctions/arm_absmin_q15.d \
./Source/StatisticsFunctions/arm_absmin_q31.d \
./Source/StatisticsFunctions/arm_absmin_q7.d \
./Source/StatisticsFunctions/arm_accumulate_f16.d \
./Source/StatisticsFunctions/arm_accumulate_f32.d \
./Source/StatisticsFunctions/arm_accumulate_f64.d \
./Source/StatisticsFunctions/arm_entropy_f16.d \
./Source/StatisticsFunctions/arm_entropy_f32.d \
./Source/StatisticsFunctions/arm_entropy_f64.d \
./Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Source/StatisticsFunctions/arm_max_f16.d \
./Source/StatisticsFunctions/arm_max_f32.d \
./Source/StatisticsFunctions/arm_max_f64.d \
./Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Source/StatisticsFunctions/arm_max_q15.d \
./Source/StatisticsFunctions/arm_max_q31.d \
./Source/StatisticsFunctions/arm_max_q7.d \
./Source/StatisticsFunctions/arm_mean_f16.d \
./Source/StatisticsFunctions/arm_mean_f32.d \
./Source/StatisticsFunctions/arm_mean_f64.d \
./Source/StatisticsFunctions/arm_mean_q15.d \
./Source/StatisticsFunctions/arm_mean_q31.d \
./Source/StatisticsFunctions/arm_mean_q7.d \
./Source/StatisticsFunctions/arm_min_f16.d \
./Source/StatisticsFunctions/arm_min_f32.d \
./Source/StatisticsFunctions/arm_min_f64.d \
./Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Source/StatisticsFunctions/arm_min_q15.d \
./Source/StatisticsFunctions/arm_min_q31.d \
./Source/StatisticsFunctions/arm_min_q7.d \
./Source/StatisticsFunctions/arm_mse_f16.d \
./Source/StatisticsFunctions/arm_mse_f32.d \
./Source/StatisticsFunctions/arm_mse_f64.d \
./Source/StatisticsFunctions/arm_mse_q15.d \
./Source/StatisticsFunctions/arm_mse_q31.d \
./Source/StatisticsFunctions/arm_mse_q7.d \
./Source/StatisticsFunctions/arm_power_f16.d \
./Source/StatisticsFunctions/arm_power_f32.d \
./Source/StatisticsFunctions/arm_power_f64.d \
./Source/StatisticsFunctions/arm_power_q15.d \
./Source/StatisticsFunctions/arm_power_q31.d \
./Source/StatisticsFunctions/arm_power_q7.d \
./Source/StatisticsFunctions/arm_rms_f16.d \
./Source/StatisticsFunctions/arm_rms_f32.d \
./Source/StatisticsFunctions/arm_rms_q15.d \
./Source/StatisticsFunctions/arm_rms_q31.d \
./Source/StatisticsFunctions/arm_std_f16.d \
./Source/StatisticsFunctions/arm_std_f32.d \
./Source/StatisticsFunctions/arm_std_f64.d \
./Source/StatisticsFunctions/arm_std_q15.d \
./Source/StatisticsFunctions/arm_std_q31.d \
./Source/StatisticsFunctions/arm_var_f16.d \
./Source/StatisticsFunctions/arm_var_f32.d \
./Source/StatisticsFunctions/arm_var_f64.d \
./Source/StatisticsFunctions/arm_var_q15.d \
./Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Source/StatisticsFunctions/%.o Source/StatisticsFunctions/%.su Source/StatisticsFunctions/%.cyclo: ../Source/StatisticsFunctions/%.c Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G474xx -c -I../Core/Inc -I../MPU6050/Src -I../micro_ros_stm32cubemx_utils/microros_static_library_ide/libmicroros/include -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/PrivateInclude/ -I../Middlewares/Third_Party/ARM_CMSIS/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/Include -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/BasicMathFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/BayesFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/CommonTables" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/ComplexMathFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/ControllerFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/DistanceFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/FastMathFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/FilteringFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/InterpolationFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/MatrixFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/QuaternionMathFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/StatisticsFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/SupportFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/SVMFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/TransformFunctions" -I"/home/ponwalai/microros_ws/firmware/mpu6050_uros/Source/WindowFunctions" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Source-2f-StatisticsFunctions

clean-Source-2f-StatisticsFunctions:
	-$(RM) ./Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Source/StatisticsFunctions/StatisticsFunctions.d ./Source/StatisticsFunctions/StatisticsFunctions.o ./Source/StatisticsFunctions/StatisticsFunctions.su ./Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Source/StatisticsFunctions/arm_absmax_f16.d ./Source/StatisticsFunctions/arm_absmax_f16.o ./Source/StatisticsFunctions/arm_absmax_f16.su ./Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Source/StatisticsFunctions/arm_absmax_f32.d ./Source/StatisticsFunctions/arm_absmax_f32.o ./Source/StatisticsFunctions/arm_absmax_f32.su ./Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Source/StatisticsFunctions/arm_absmax_f64.d ./Source/StatisticsFunctions/arm_absmax_f64.o ./Source/StatisticsFunctions/arm_absmax_f64.su ./Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Source/StatisticsFunctions/arm_absmax_q15.d ./Source/StatisticsFunctions/arm_absmax_q15.o ./Source/StatisticsFunctions/arm_absmax_q15.su ./Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Source/StatisticsFunctions/arm_absmax_q31.d ./Source/StatisticsFunctions/arm_absmax_q31.o ./Source/StatisticsFunctions/arm_absmax_q31.su ./Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Source/StatisticsFunctions/arm_absmax_q7.d ./Source/StatisticsFunctions/arm_absmax_q7.o ./Source/StatisticsFunctions/arm_absmax_q7.su ./Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Source/StatisticsFunctions/arm_absmin_f16.d ./Source/StatisticsFunctions/arm_absmin_f16.o ./Source/StatisticsFunctions/arm_absmin_f16.su ./Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Source/StatisticsFunctions/arm_absmin_f32.d ./Source/StatisticsFunctions/arm_absmin_f32.o ./Source/StatisticsFunctions/arm_absmin_f32.su ./Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Source/StatisticsFunctions/arm_absmin_f64.d ./Source/StatisticsFunctions/arm_absmin_f64.o ./Source/StatisticsFunctions/arm_absmin_f64.su ./Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Source/StatisticsFunctions/arm_absmin_q15.d ./Source/StatisticsFunctions/arm_absmin_q15.o ./Source/StatisticsFunctions/arm_absmin_q15.su ./Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Source/StatisticsFunctions/arm_absmin_q31.d ./Source/StatisticsFunctions/arm_absmin_q31.o ./Source/StatisticsFunctions/arm_absmin_q31.su ./Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Source/StatisticsFunctions/arm_absmin_q7.d ./Source/StatisticsFunctions/arm_absmin_q7.o ./Source/StatisticsFunctions/arm_absmin_q7.su ./Source/StatisticsFunctions/arm_accumulate_f16.cyclo ./Source/StatisticsFunctions/arm_accumulate_f16.d ./Source/StatisticsFunctions/arm_accumulate_f16.o ./Source/StatisticsFunctions/arm_accumulate_f16.su ./Source/StatisticsFunctions/arm_accumulate_f32.cyclo ./Source/StatisticsFunctions/arm_accumulate_f32.d ./Source/StatisticsFunctions/arm_accumulate_f32.o ./Source/StatisticsFunctions/arm_accumulate_f32.su ./Source/StatisticsFunctions/arm_accumulate_f64.cyclo ./Source/StatisticsFunctions/arm_accumulate_f64.d ./Source/StatisticsFunctions/arm_accumulate_f64.o ./Source/StatisticsFunctions/arm_accumulate_f64.su ./Source/StatisticsFunctions/arm_entropy_f16.cyclo
	-$(RM) ./Source/StatisticsFunctions/arm_entropy_f16.d ./Source/StatisticsFunctions/arm_entropy_f16.o ./Source/StatisticsFunctions/arm_entropy_f16.su ./Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Source/StatisticsFunctions/arm_entropy_f32.d ./Source/StatisticsFunctions/arm_entropy_f32.o ./Source/StatisticsFunctions/arm_entropy_f32.su ./Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Source/StatisticsFunctions/arm_entropy_f64.d ./Source/StatisticsFunctions/arm_entropy_f64.o ./Source/StatisticsFunctions/arm_entropy_f64.su ./Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Source/StatisticsFunctions/arm_logsumexp_f16.d ./Source/StatisticsFunctions/arm_logsumexp_f16.o ./Source/StatisticsFunctions/arm_logsumexp_f16.su ./Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Source/StatisticsFunctions/arm_logsumexp_f32.d ./Source/StatisticsFunctions/arm_logsumexp_f32.o ./Source/StatisticsFunctions/arm_logsumexp_f32.su ./Source/StatisticsFunctions/arm_max_f16.cyclo ./Source/StatisticsFunctions/arm_max_f16.d ./Source/StatisticsFunctions/arm_max_f16.o ./Source/StatisticsFunctions/arm_max_f16.su ./Source/StatisticsFunctions/arm_max_f32.cyclo ./Source/StatisticsFunctions/arm_max_f32.d ./Source/StatisticsFunctions/arm_max_f32.o ./Source/StatisticsFunctions/arm_max_f32.su ./Source/StatisticsFunctions/arm_max_f64.cyclo ./Source/StatisticsFunctions/arm_max_f64.d ./Source/StatisticsFunctions/arm_max_f64.o ./Source/StatisticsFunctions/arm_max_f64.su ./Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Source/StatisticsFunctions/arm_max_q15.cyclo ./Source/StatisticsFunctions/arm_max_q15.d ./Source/StatisticsFunctions/arm_max_q15.o ./Source/StatisticsFunctions/arm_max_q15.su ./Source/StatisticsFunctions/arm_max_q31.cyclo ./Source/StatisticsFunctions/arm_max_q31.d ./Source/StatisticsFunctions/arm_max_q31.o ./Source/StatisticsFunctions/arm_max_q31.su ./Source/StatisticsFunctions/arm_max_q7.cyclo ./Source/StatisticsFunctions/arm_max_q7.d ./Source/StatisticsFunctions/arm_max_q7.o ./Source/StatisticsFunctions/arm_max_q7.su ./Source/StatisticsFunctions/arm_mean_f16.cyclo ./Source/StatisticsFunctions/arm_mean_f16.d ./Source/StatisticsFunctions/arm_mean_f16.o ./Source/StatisticsFunctions/arm_mean_f16.su ./Source/StatisticsFunctions/arm_mean_f32.cyclo ./Source/StatisticsFunctions/arm_mean_f32.d ./Source/StatisticsFunctions/arm_mean_f32.o ./Source/StatisticsFunctions/arm_mean_f32.su ./Source/StatisticsFunctions/arm_mean_f64.cyclo ./Source/StatisticsFunctions/arm_mean_f64.d ./Source/StatisticsFunctions/arm_mean_f64.o ./Source/StatisticsFunctions/arm_mean_f64.su ./Source/StatisticsFunctions/arm_mean_q15.cyclo ./Source/StatisticsFunctions/arm_mean_q15.d ./Source/StatisticsFunctions/arm_mean_q15.o ./Source/StatisticsFunctions/arm_mean_q15.su ./Source/StatisticsFunctions/arm_mean_q31.cyclo ./Source/StatisticsFunctions/arm_mean_q31.d ./Source/StatisticsFunctions/arm_mean_q31.o ./Source/StatisticsFunctions/arm_mean_q31.su ./Source/StatisticsFunctions/arm_mean_q7.cyclo ./Source/StatisticsFunctions/arm_mean_q7.d ./Source/StatisticsFunctions/arm_mean_q7.o ./Source/StatisticsFunctions/arm_mean_q7.su ./Source/StatisticsFunctions/arm_min_f16.cyclo ./Source/StatisticsFunctions/arm_min_f16.d ./Source/StatisticsFunctions/arm_min_f16.o ./Source/StatisticsFunctions/arm_min_f16.su ./Source/StatisticsFunctions/arm_min_f32.cyclo ./Source/StatisticsFunctions/arm_min_f32.d ./Source/StatisticsFunctions/arm_min_f32.o ./Source/StatisticsFunctions/arm_min_f32.su ./Source/StatisticsFunctions/arm_min_f64.cyclo ./Source/StatisticsFunctions/arm_min_f64.d ./Source/StatisticsFunctions/arm_min_f64.o ./Source/StatisticsFunctions/arm_min_f64.su
	-$(RM) ./Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Source/StatisticsFunctions/arm_min_q15.cyclo ./Source/StatisticsFunctions/arm_min_q15.d ./Source/StatisticsFunctions/arm_min_q15.o ./Source/StatisticsFunctions/arm_min_q15.su ./Source/StatisticsFunctions/arm_min_q31.cyclo ./Source/StatisticsFunctions/arm_min_q31.d ./Source/StatisticsFunctions/arm_min_q31.o ./Source/StatisticsFunctions/arm_min_q31.su ./Source/StatisticsFunctions/arm_min_q7.cyclo ./Source/StatisticsFunctions/arm_min_q7.d ./Source/StatisticsFunctions/arm_min_q7.o ./Source/StatisticsFunctions/arm_min_q7.su ./Source/StatisticsFunctions/arm_mse_f16.cyclo ./Source/StatisticsFunctions/arm_mse_f16.d ./Source/StatisticsFunctions/arm_mse_f16.o ./Source/StatisticsFunctions/arm_mse_f16.su ./Source/StatisticsFunctions/arm_mse_f32.cyclo ./Source/StatisticsFunctions/arm_mse_f32.d ./Source/StatisticsFunctions/arm_mse_f32.o ./Source/StatisticsFunctions/arm_mse_f32.su ./Source/StatisticsFunctions/arm_mse_f64.cyclo ./Source/StatisticsFunctions/arm_mse_f64.d ./Source/StatisticsFunctions/arm_mse_f64.o ./Source/StatisticsFunctions/arm_mse_f64.su ./Source/StatisticsFunctions/arm_mse_q15.cyclo ./Source/StatisticsFunctions/arm_mse_q15.d ./Source/StatisticsFunctions/arm_mse_q15.o ./Source/StatisticsFunctions/arm_mse_q15.su ./Source/StatisticsFunctions/arm_mse_q31.cyclo ./Source/StatisticsFunctions/arm_mse_q31.d ./Source/StatisticsFunctions/arm_mse_q31.o ./Source/StatisticsFunctions/arm_mse_q31.su ./Source/StatisticsFunctions/arm_mse_q7.cyclo ./Source/StatisticsFunctions/arm_mse_q7.d ./Source/StatisticsFunctions/arm_mse_q7.o ./Source/StatisticsFunctions/arm_mse_q7.su ./Source/StatisticsFunctions/arm_power_f16.cyclo ./Source/StatisticsFunctions/arm_power_f16.d ./Source/StatisticsFunctions/arm_power_f16.o ./Source/StatisticsFunctions/arm_power_f16.su ./Source/StatisticsFunctions/arm_power_f32.cyclo ./Source/StatisticsFunctions/arm_power_f32.d ./Source/StatisticsFunctions/arm_power_f32.o ./Source/StatisticsFunctions/arm_power_f32.su ./Source/StatisticsFunctions/arm_power_f64.cyclo ./Source/StatisticsFunctions/arm_power_f64.d ./Source/StatisticsFunctions/arm_power_f64.o ./Source/StatisticsFunctions/arm_power_f64.su ./Source/StatisticsFunctions/arm_power_q15.cyclo ./Source/StatisticsFunctions/arm_power_q15.d ./Source/StatisticsFunctions/arm_power_q15.o ./Source/StatisticsFunctions/arm_power_q15.su ./Source/StatisticsFunctions/arm_power_q31.cyclo ./Source/StatisticsFunctions/arm_power_q31.d ./Source/StatisticsFunctions/arm_power_q31.o ./Source/StatisticsFunctions/arm_power_q31.su ./Source/StatisticsFunctions/arm_power_q7.cyclo ./Source/StatisticsFunctions/arm_power_q7.d ./Source/StatisticsFunctions/arm_power_q7.o ./Source/StatisticsFunctions/arm_power_q7.su ./Source/StatisticsFunctions/arm_rms_f16.cyclo ./Source/StatisticsFunctions/arm_rms_f16.d ./Source/StatisticsFunctions/arm_rms_f16.o ./Source/StatisticsFunctions/arm_rms_f16.su ./Source/StatisticsFunctions/arm_rms_f32.cyclo ./Source/StatisticsFunctions/arm_rms_f32.d ./Source/StatisticsFunctions/arm_rms_f32.o ./Source/StatisticsFunctions/arm_rms_f32.su ./Source/StatisticsFunctions/arm_rms_q15.cyclo ./Source/StatisticsFunctions/arm_rms_q15.d ./Source/StatisticsFunctions/arm_rms_q15.o ./Source/StatisticsFunctions/arm_rms_q15.su ./Source/StatisticsFunctions/arm_rms_q31.cyclo ./Source/StatisticsFunctions/arm_rms_q31.d ./Source/StatisticsFunctions/arm_rms_q31.o ./Source/StatisticsFunctions/arm_rms_q31.su ./Source/StatisticsFunctions/arm_std_f16.cyclo ./Source/StatisticsFunctions/arm_std_f16.d ./Source/StatisticsFunctions/arm_std_f16.o ./Source/StatisticsFunctions/arm_std_f16.su ./Source/StatisticsFunctions/arm_std_f32.cyclo ./Source/StatisticsFunctions/arm_std_f32.d ./Source/StatisticsFunctions/arm_std_f32.o ./Source/StatisticsFunctions/arm_std_f32.su ./Source/StatisticsFunctions/arm_std_f64.cyclo ./Source/StatisticsFunctions/arm_std_f64.d ./Source/StatisticsFunctions/arm_std_f64.o ./Source/StatisticsFunctions/arm_std_f64.su ./Source/StatisticsFunctions/arm_std_q15.cyclo ./Source/StatisticsFunctions/arm_std_q15.d ./Source/StatisticsFunctions/arm_std_q15.o ./Source/StatisticsFunctions/arm_std_q15.su ./Source/StatisticsFunctions/arm_std_q31.cyclo ./Source/StatisticsFunctions/arm_std_q31.d ./Source/StatisticsFunctions/arm_std_q31.o ./Source/StatisticsFunctions/arm_std_q31.su ./Source/StatisticsFunctions/arm_var_f16.cyclo ./Source/StatisticsFunctions/arm_var_f16.d ./Source/StatisticsFunctions/arm_var_f16.o ./Source/StatisticsFunctions/arm_var_f16.su ./Source/StatisticsFunctions/arm_var_f32.cyclo ./Source/StatisticsFunctions/arm_var_f32.d ./Source/StatisticsFunctions/arm_var_f32.o ./Source/StatisticsFunctions/arm_var_f32.su ./Source/StatisticsFunctions/arm_var_f64.cyclo ./Source/StatisticsFunctions/arm_var_f64.d
	-$(RM) ./Source/StatisticsFunctions/arm_var_f64.o ./Source/StatisticsFunctions/arm_var_f64.su ./Source/StatisticsFunctions/arm_var_q15.cyclo ./Source/StatisticsFunctions/arm_var_q15.d ./Source/StatisticsFunctions/arm_var_q15.o ./Source/StatisticsFunctions/arm_var_q15.su ./Source/StatisticsFunctions/arm_var_q31.cyclo ./Source/StatisticsFunctions/arm_var_q31.d ./Source/StatisticsFunctions/arm_var_q31.o ./Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Source-2f-StatisticsFunctions

